/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1.blottersystem;

import javax.swing.JTextArea;
import java.awt.Color;
import java.awt.Dimension;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

 
/**
 *
 * @author Win10
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
     
    public Dashboard() {
        initComponents();
        dt();
       
        
          Image img= new ImageIcon(this.getClass().getResource("/logo.png")).getImage();
        this.setIconImage(img);
    }
    
    public void dt(){
    
        Date d = new Date();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
        
        String dd = sdf.format(d);
        l_date.setText(dd);
    }
    
  
    public void fileWriter() {
        try (FileWriter writer = new FileWriter("Database.txt", true)) { // true appends to the file
            // Retrieve the text from the text field and write it to the file
            String complainantName = Complainant_Name.getText();
            String complainee = Complainee.getText();
            String Whowasinvolved = Who_was_involved.getText();
            String WhenAndWhereItTookPlace = When_and_where_it_took_place.getText();
            String DescribeWhatHappened = Describe_what_happened.getText();
            if (complainantName.isEmpty() || complainee.isEmpty() || Whowasinvolved.isEmpty() || WhenAndWhereItTookPlace.isEmpty() || DescribeWhatHappened.isEmpty()) {
                JOptionPane.showMessageDialog(null, "The name field cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
                writer.write(complainantName + "/" +  complainee + "/" + Whowasinvolved + "/"
                + WhenAndWhereItTookPlace + "/" + DescribeWhatHappened + System.lineSeparator());
                
                loadDatabase();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while saving your response: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        View_All_Arrests = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        File_a_report = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Update = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        View_Incident_Reports = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        p2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textDetails3 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textDetails4 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        textDetails5 = new javax.swing.JTextArea();
        jTextArea6 = new javax.swing.JTextArea();
        p3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Who_was_involved = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        When_and_where_it_took_place = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Complainant_Name = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Complainee = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Describe_what_happened = new javax.swing.JTextField();
        p5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        whoWasInvolved = new javax.swing.JTextField();
        complainantName = new javax.swing.JTextField();
        complainee = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextArea = new javax.swing.JTextArea();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 72, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Trece Martires City E-Blotter System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 15, 467, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 70));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jButton2.setText("Account Profile");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 161, 56));

        View_All_Arrests.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        View_All_Arrests.setText("View All Arrests");
        View_All_Arrests.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        View_All_Arrests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View_All_Arrests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_All_ArrestsMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analysis.png"))); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View_All_Arrests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(View_All_Arrests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 402, -1));

        File_a_report.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        File_a_report.setText("File A Report");
        File_a_report.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        File_a_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        File_a_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                File_a_reportMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporrt.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(File_a_report, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(File_a_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setText("Updates");
        Update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notif.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        View_Incident_Reports.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        View_Incident_Reports.setText("View Incident Reports");
        View_Incident_Reports.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        View_Incident_Reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View_Incident_Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_Incident_ReportsMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporrt.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(View_Incident_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_Incident_Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, -1));

        l_date.setText("Date: ");
        jPanel3.add(l_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel4.setText("Date: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        Logout.setBackground(new java.awt.Color(255, 153, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Close");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel3.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 660));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textDetails3.setBackground(new java.awt.Color(255, 255, 255));
        textDetails3.setColumns(20);
        textDetails3.setForeground(new java.awt.Color(0, 0, 0));
        textDetails3.setRows(5);
        textDetails3.setText("NAME: ARTHUR NERI\nCRIME: THEFT\nAGE: 20\nBIRTHDAY: OCTOBER 20, 2004\nNATIONALITY: FILIPINO\nPHYSICAL DESCRIPTION:\n- SKIN-COLOR: WHITE\n- EYE-COLOR: BROWN\n- HEIGHT: 160 CM\n- WEIGHT: 60 KG");
        jScrollPane7.setViewportView(textDetails3);

        p2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 220, 180));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mugshot.jpg"))); // NOI18N
        p2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mugshot.jpg"))); // NOI18N
        p2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        textDetails4.setBackground(new java.awt.Color(255, 255, 255));
        textDetails4.setColumns(20);
        textDetails4.setForeground(new java.awt.Color(0, 0, 0));
        textDetails4.setRows(5);
        textDetails4.setText("NAME: ARTHUR NERI\nCRIME: THEFT\nAGE: 20\nBIRTHDAY: OCTOBER 20, 2004\nNATIONALITY: FILIPINO\nPHYSICAL DESCRIPTION:\n- SKIN-COLOR: WHITE\n- EYE-COLOR: BROWN\n- HEIGHT: 160 CM\n- WEIGHT: 60 KG");
        jScrollPane8.setViewportView(textDetails4);

        p2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 220, 180));

        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText("");
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 240, 380));

        jTextArea5.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea5.setRows(5);
        jTextArea5.setToolTipText("");
        jTextArea5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.add(jTextArea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 240, 380));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mugshot.jpg"))); // NOI18N
        p2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, -1));

        textDetails5.setBackground(new java.awt.Color(255, 255, 255));
        textDetails5.setColumns(20);
        textDetails5.setForeground(new java.awt.Color(0, 0, 0));
        textDetails5.setRows(5);
        textDetails5.setText("NAME: ARTHUR NERI\nCRIME: THEFT\nAGE: 20\nBIRTHDAY: OCTOBER 20, 2004\nNATIONALITY: FILIPINO\nPHYSICAL DESCRIPTION:\n- SKIN-COLOR: WHITE\n- EYE-COLOR: BROWN\n- HEIGHT: 160 CM\n- WEIGHT: 60 KG");
        jScrollPane9.setViewportView(textDetails5);

        p2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 220, 180));

        jTextArea6.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea6.setRows(5);
        jTextArea6.setToolTipText("");
        jTextArea6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2.add(jTextArea6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 240, 380));

        jTabbedPane1.addTab("tab0", p2);

        p3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("What's New?");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j5.jpg"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j1.jpg"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("BJMP News");

        jLabel28.setText("jLabel28");

        jLabel29.setText("Catch up with the Latest news in Trece Martires City, Cavite!");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("BJMP NEWS");

        jLabel31.setText("jLabel31");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j2.jpg"))); // NOI18N
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Trece Martires News!");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(578, 578, 578)
                        .addComponent(jLabel27))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30)))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1685, 1685, 1685)
                                .addComponent(jLabel31)
                                .addGap(2576, 2576, 2576)
                                .addComponent(jLabel28)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel28))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(jLabel33))
                            .addComponent(jLabel24)
                            .addComponent(jLabel30)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)))
                .addGap(213, 213, 213)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", p3);

        p4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Report Incident");

        jLabel18.setText("Who was involved?");

        Who_was_involved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Who_was_involvedActionPerformed(evt);
            }
        });

        jLabel19.setText("When and where it took place?");

        When_and_where_it_took_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                When_and_where_it_took_placeActionPerformed(evt);
            }
        });

        jLabel20.setText("Describe what happened.");

        jLabel21.setText("Complainant Name:");

        Complainant_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Complainant_NameActionPerformed(evt);
            }
        });

        jLabel22.setText("Complainee: ");

        Complainee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplaineeActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Submit");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j4.png"))); // NOI18N
        jLabel25.setText("jLabel25");

        Describe_what_happened.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Describe_what_happened.setToolTipText("");
        Describe_what_happened.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Describe_what_happenedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Describe_what_happened, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Complainee, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(Complainant_Name)
                    .addComponent(jLabel20)
                    .addComponent(jButton3)
                    .addComponent(When_and_where_it_took_place)
                    .addComponent(Who_was_involved))
                .addGap(91, 91, 91)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addComponent(Complainant_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Complainee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Who_was_involved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(When_and_where_it_took_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(Describe_what_happened, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab2", p4);

        p5.setBackground(new java.awt.Color(255, 255, 255));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Who was involved?");
        p5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 70));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Find Incident");
        p5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 240, 70));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Complainant Name:");
        p5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, 70));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Complainee: ");
        p5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 70));

        submit.setBackground(new java.awt.Color(255, 153, 0));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        p5.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 90, 30));

        whoWasInvolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whoWasInvolvedActionPerformed(evt);
            }
        });
        p5.add(whoWasInvolved, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 170, 30));

        complainantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainantNameActionPerformed(evt);
            }
        });
        p5.add(complainantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 170, 30));

        complainee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaineeActionPerformed(evt);
            }
        });
        p5.add(complainee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 170, 30));

        jTabbedPane1.addTab("tab3", p5);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel10.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        JTextArea.setColumns(20);
        JTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JTextArea.setRows(5);
        jScrollPane1.setViewportView(JTextArea);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 890, 570));

        jTabbedPane1.addTab("tab4", jPanel10);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 960, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login l = new Login();
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EditProfile ep = new EditProfile();
        dispose();
        ep.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void View_All_ArrestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_All_ArrestsMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_View_All_ArrestsMouseClicked

    private void View_Incident_ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_Incident_ReportsMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_View_Incident_ReportsMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_UpdateMouseClicked

    private void File_a_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_File_a_reportMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_File_a_reportMouseClicked

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        loadDatabase();
    }//GEN-LAST:event_refreshActionPerformed

    private void complaineeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaineeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complaineeActionPerformed

    private void complainantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainantNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainantNameActionPerformed

    private void whoWasInvolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whoWasInvolvedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whoWasInvolvedActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String complainantNames = complainantName.getText(); // Get the text from complainant name
        String complainees = complainee.getText(); // Get the text from complainee name
        String whoWasInvolve = whoWasInvolved.getText(); // Get the text from involved person

        String filePath = "Database.txt"; // Path to the database file

        boolean reportFound = false; // Flag to indicate if the report is found

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;

            // Read through each line in the file
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("/");
                // Match each part of the line separately
                if (parts.length >= 3) {
                    String fileComplainant = parts[0].trim();
                    String fileComplainee = parts[1].trim();
                    String fileInvolved = parts[2].trim();

                    // Check if the extracted parts match the user input
                    if (fileComplainant.equalsIgnoreCase(complainantNames) &&
                        fileComplainee.equalsIgnoreCase(complainees) &&
                        fileInvolved.equalsIgnoreCase(whoWasInvolve)) {
                        reportFound = true;
                        break;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error reading the file: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (reportFound) {
            JOptionPane.showMessageDialog(null, "Report Found!");
            jTabbedPane1.setSelectedIndex(4); 
        } else {
            JOptionPane.showMessageDialog(null, "Report Not Found.");
            jTabbedPane1.setSelectedIndex(2); // Go to tab 2 (dashboard)

        }
    }//GEN-LAST:event_submitActionPerformed

    private void Describe_what_happenedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Describe_what_happenedActionPerformed

    }//GEN-LAST:event_Describe_what_happenedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fileWriter(); // Write the content of Complainant_Name to the file
        JOptionPane.showMessageDialog(null, "Your Response, Has been Successfully Recorded. Thank you!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ComplaineeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplaineeActionPerformed

    }//GEN-LAST:event_ComplaineeActionPerformed

    private void Complainant_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Complainant_NameActionPerformed

    }//GEN-LAST:event_Complainant_NameActionPerformed

    private void When_and_where_it_took_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_When_and_where_it_took_placeActionPerformed

    }//GEN-LAST:event_When_and_where_it_took_placeActionPerformed

    private void Who_was_involvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Who_was_involvedActionPerformed

    }//GEN-LAST:event_Who_was_involvedActionPerformed

    private void loadDatabase() {
    // Ensure the JScrollPane has a JPanel as its viewport view
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS)); // Vertical layout for text areas
    jScrollPane1.setViewportView(panel); // Set the panel as the viewport view of the JScrollPane
    String[] customLabels = {"Complainant Name: ", "Complainee: ", "Who was involved? ", "When and where it took place? ", "Describe what happened: "};

    try (BufferedReader br = new BufferedReader(new FileReader("Database.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            // Split the line (assuming CSV format)
            String[] fields = line.split("/");
            
            StringBuilder formattedText = new StringBuilder();

            // Add labels before each field
            for (int i = 0; i < fields.length; i++) {
                String label = i < customLabels.length ? customLabels[i] : "Field " + (i + 1) + ": ";
                formattedText.append(label).append(fields[i].trim()).append("\n");
            }
            
            JTextArea textArea = new JTextArea();
            textArea.setText(formattedText.toString().trim()); // Display each field on a new line
            textArea.setLineWrap(true);
            textArea.setWrapStyleWord(true);
            textArea.setEditable(false);
            textArea.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            textArea.setPreferredSize(new Dimension(400, 100)); // Set size for the text area

            // Add the text area to the panel
            panel.add(textArea);
            panel.add(Box.createRigidArea(new Dimension(0, 10))); // Add spacing between text areas
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error loading database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Refresh the panel
    panel.revalidate();
    panel.repaint();
}

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Complainant_Name;
    private javax.swing.JTextField Complainee;
    private javax.swing.JTextField Describe_what_happened;
    private javax.swing.JLabel File_a_report;
    private javax.swing.JTextArea JTextArea;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel Update;
    private javax.swing.JLabel View_All_Arrests;
    private javax.swing.JLabel View_Incident_Reports;
    private javax.swing.JTextField When_and_where_it_took_place;
    private javax.swing.JTextField Who_was_involved;
    private javax.swing.JTextField complainantName;
    private javax.swing.JTextField complainee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JLabel l_date;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JButton refresh;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea textDetails3;
    private javax.swing.JTextArea textDetails4;
    private javax.swing.JTextArea textDetails5;
    private javax.swing.JTextField whoWasInvolved;
    // End of variables declaration//GEN-END:variables
}
